# The join message for all players
join-message: "&aWelcome to the server %player%!"

# Join sound settings
join-sound:
  enabled: true
  sound: "ENTITY_PLAYER_LEVELUP"

# Random join messages
random-join-messages:
  enabled: false
  messages:
    - "&a%player% just showed up... try to act normal."
    - "&a%player% hatched into the world!"
    - "&a%player% has joined the simulation."
    - "&a%player% arrived, but only for the free pizza."