name: EpicGreetings
version: '1.0-SNAPSHOT'
main: com.tanner.epicGreetings.EpicGreetings
api-version: '1.21'
permissions:
  epicgreetings.use:
    description: This permission allows the user to use the commands for this plugin
commands:
  epicgreetings:
    description: Has a help option to list all commands.
  setjoinmessage:
    description: Configure the join message from in-game. This will update the config with whatever you set.
  joinsound:
    description: Configure the join sound from in-game. This will update the config with whatever you set.
  randomjoinmessage:
    description: Configure random join messages.